# Generated by Django 3.1.7 on 2021-03-18 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='customer.customer')),
                ('rating', models.FloatField(blank=True, default=5, null=True)),
                ('time_rating', models.BigIntegerField(blank=True, null=True)),
                ('movie', models.ForeignKey(default=8, on_delete=django.db.models.deletion.DO_NOTHING, to='movie.movies')),
            ],
            options={
                'db_table': 'ratings',
                'managed': True,
                'unique_together': {('user', 'movie')},
            },
        ),
    ]
