# Generated by Django 3.1.7 on 2021-03-26 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20210318_1421'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'managed': False},
        ),
    ]
